/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employeedatabase;

import java.awt.Font;
import java.sql.*;
import java.awt.*;
import java.io.*;

/**
 *
 * @author Steven
 */
public class DatabaseFrame extends javax.swing.JFrame {

    /**
     * Creates new form DatabaseFrame
     */
    public DatabaseFrame() {
        initComponents();
        this.lblHeading.setText("Employee Form");
        java.awt.Font font = new java.awt.Font(lblHeading.getText(),Font.BOLD,23);
        this.lblHeading.setFont(font);
        this.txtTableColumns.setFont(new Font("monospaced",Font.PLAIN,12));
        connectToDatabase();
        metaPopulate();
       
    }

    Connection con;
    Statement stmt = null;
    Connector connect = new Connector();
    ResultSet rs = null;
    
    //Initiate app to populatefields
    public void connectToDatabase(){
        try{
            con = connect.connectToDatabase();
            String sql = "SELECT * FROM empdetail";
            stmt = con.createStatement();
            rs = stmt.executeQuery(sql);
            rs.next();
            txtEmpNo.setText(rs.getString("EmpID"));
            txtName.setText(rs.getString("EmpName"));
            txtAddress.setText(rs.getString("Address"));
            txtSuburb.setText(rs.getString("Suburb"));
            txtPostcode.setText(rs.getString("Postcode"));
            txtPhone.setText(rs.getString("HomePhone"));
            txtMobile.setText(rs.getString("Mobile"));
            txtEmail.setText(rs.getString("Email"));
            
            stmt.close();
            connect.closeConnection(con);
        }
        catch(SQLException sqle){
            msgMessage.showMessageDialog(this,sqle.toString()+"close","Message",javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
        }
    public void metaPopulate(){
        try{ 
            con = connect.connectToDatabase();
            stmt = con.createStatement();
            String sql = "SELECT * FROM empdetail";
            rs = stmt.executeQuery(sql);
            ResultSetMetaData rsMetaData = rs.getMetaData();
            DatabaseMetaData dbMetaData = con.getMetaData();
            
            txtDbType.setText(dbMetaData.getDatabaseProductName());
            txtDbVersion.setText(dbMetaData.getDatabaseProductVersion());
            DbDriver.setText(dbMetaData.getDriverName());
            txtTableName.setText(rsMetaData.getTableName(1));
            String space =" ";
            
            
            for(int i =1 ; i<rsMetaData.getColumnCount()+1;i++){
                String left = rsMetaData.getColumnName(i);
                String right = rsMetaData.getColumnTypeName(i)+"\n";
                String line = String.format("%1$-10s %2$10s", left,right);    
                txtTableColumns.setText(txtTableColumns.getText()+line);
            }
            
            connect.closeConnection(con);
        }
        catch(SQLException sqle){
            msgMessage.showMessageDialog(this,sqle.toString(),"Error Message",javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        msgMessage = new javax.swing.JOptionPane();
        lblHeading = new javax.swing.JLabel();
        panEmployeeDetails = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtEmpNo = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtSuburb = new javax.swing.JTextField();
        txtPostcode = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtMobile = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        btnNew = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnRetrieve = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        panQuery = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtQuery = new javax.swing.JTextField();
        btnSubmitQuery = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtNumberOfRecord = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtFilePath = new javax.swing.JTextField();
        btnReport = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDetails = new javax.swing.JTable();
        panMetaData = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtTableColumns = new javax.swing.JTextArea();
        txtDbType = new javax.swing.JTextField();
        txtDbVersion = new javax.swing.JTextField();
        DbDriver = new javax.swing.JTextField();
        txtTableName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblHeading.setText("jLabel1");

        panEmployeeDetails.setBorder(javax.swing.BorderFactory.createTitledBorder("Employee Details"));

        jLabel2.setText("Employee No:");

        jLabel3.setText("Name:");

        jLabel4.setText("Address:");

        jLabel5.setText("Suburb:");

        jLabel6.setText("Postcode:");

        jLabel7.setText("Phone (Home):");

        jLabel8.setText("Mobile:");

        jLabel9.setText("Email:");

        txtSuburb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSuburbActionPerformed(evt);
            }
        });

        btnNew.setText("New");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnRetrieve.setText("Retrive");
        btnRetrieve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetrieveActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panEmployeeDetailsLayout = new javax.swing.GroupLayout(panEmployeeDetails);
        panEmployeeDetails.setLayout(panEmployeeDetailsLayout);
        panEmployeeDetailsLayout.setHorizontalGroup(
            panEmployeeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEmployeeDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panEmployeeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panEmployeeDetailsLayout.createSequentialGroup()
                        .addGroup(panEmployeeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(46, 46, 46)
                        .addGroup(panEmployeeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPostcode, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSuburb, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmpNo, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panEmployeeDetailsLayout.createSequentialGroup()
                        .addComponent(btnNew, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRetrieve)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))))
        );
        panEmployeeDetailsLayout.setVerticalGroup(
            panEmployeeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEmployeeDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panEmployeeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtEmpNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panEmployeeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panEmployeeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panEmployeeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSuburb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panEmployeeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPostcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panEmployeeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(panEmployeeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panEmployeeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(panEmployeeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNew)
                    .addComponent(btnAdd)
                    .addComponent(btnRetrieve)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)))
        );

        panQuery.setBorder(javax.swing.BorderFactory.createTitledBorder("Query"));

        jLabel1.setText("Query:");

        btnSubmitQuery.setText("Submit Query");
        btnSubmitQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitQueryActionPerformed(evt);
            }
        });

        jLabel10.setText("Results:");

        jLabel11.setText("Number of Records: ");

        txtNumberOfRecord.setEditable(false);

        jLabel12.setText("Report File:");

        btnReport.setText("Report File");
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });

        tblDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tblDetails);

        javax.swing.GroupLayout panQueryLayout = new javax.swing.GroupLayout(panQuery);
        panQuery.setLayout(panQueryLayout);
        panQueryLayout.setHorizontalGroup(
            panQueryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panQueryLayout.createSequentialGroup()
                .addGroup(panQueryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panQueryLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(59, 59, 59)
                        .addComponent(txtFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addComponent(btnReport, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panQueryLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panQueryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panQueryLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtQuery, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panQueryLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(panQueryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSubmitQuery, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panQueryLayout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(32, 32, 32)
                                        .addComponent(txtNumberOfRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(panQueryLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane3))))
                .addContainerGap())
        );
        panQueryLayout.setVerticalGroup(
            panQueryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panQueryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panQueryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtQuery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSubmitQuery)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(panQueryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtNumberOfRecord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panQueryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReport))
                .addGap(39, 39, 39))
        );

        panMetaData.setBorder(javax.swing.BorderFactory.createTitledBorder("Meta Data"));

        jLabel13.setText("Database Type:");

        jLabel14.setText("Database Version:");

        jLabel15.setText("Database Driver:");

        jLabel16.setText("Table Name: ");

        jLabel17.setText("Table Columns:");

        txtTableColumns.setEditable(false);
        txtTableColumns.setColumns(20);
        txtTableColumns.setRows(5);
        jScrollPane2.setViewportView(txtTableColumns);

        txtDbType.setEditable(false);

        txtDbVersion.setEditable(false);

        DbDriver.setEditable(false);

        txtTableName.setEditable(false);

        javax.swing.GroupLayout panMetaDataLayout = new javax.swing.GroupLayout(panMetaData);
        panMetaData.setLayout(panMetaDataLayout);
        panMetaDataLayout.setHorizontalGroup(
            panMetaDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMetaDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panMetaDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGap(25, 25, 25)
                .addGroup(panMetaDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTableName)
                    .addComponent(DbDriver)
                    .addComponent(txtDbVersion, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                    .addComponent(txtDbType)
                    .addComponent(jScrollPane2))
                .addGap(13, 13, 13))
        );
        panMetaDataLayout.setVerticalGroup(
            panMetaDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMetaDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panMetaDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtDbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panMetaDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtDbVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panMetaDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(DbDriver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panMetaDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtTableName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panMetaDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHeading)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panMetaData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panEmployeeDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panQuery, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHeading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panEmployeeDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panMetaData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(panQuery, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        try{
            con = connect.connectToDatabase();
            stmt = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
            String sql = "SELECT EmpID FROM empdetail";
            rs = stmt.executeQuery(sql);
            rs.last();
            txtEmpNo.setText(String.valueOf(rs.getInt("EmpID")+1));
            txtName.setText("");
            txtAddress.setText("");
            txtSuburb.setText("");
            txtPostcode.setText("");
            txtPhone.setText("");
            txtMobile.setText("");
            txtEmail.setText("");
            stmt.close();
            con.close();
        }
        catch(SQLException sqle){
            msgMessage.showMessageDialog(this,sqle.toString(),"Error Message",javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try{
            con = connect.connectToDatabase();
            stmt = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
            String sql = "INSERT INTO empdetail (EmpID,EmpName,Address,Suburb,Postcode,HomePhone,Mobile,Email)VALUES('";
            sql += txtEmpNo.getText()+"', '";
            sql += txtName.getText()+"', '";
            sql += txtAddress.getText()+"', '";
            sql += txtSuburb.getText()+"', '";
            sql += txtPostcode.getText()+"', '";
            sql += txtPhone.getText()+"', '";
            sql += txtMobile.getText()+"', '";
            sql += txtEmail.getText()+"')";
            stmt.executeUpdate(sql);
            msgMessage.showMessageDialog(this,"Record added to current table suucessfuly","Message",javax.swing.JOptionPane.INFORMATION_MESSAGE);
            stmt.close();
            connect.closeConnection(con);
        }
    catch(SQLException sqle){
        msgMessage.showMessageDialog(this,sqle.toString(),"Error Message",javax.swing.JOptionPane.ERROR_MESSAGE);
    }                
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnRetrieveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetrieveActionPerformed
        try{
            con = connect.connectToDatabase();
            stmt = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
            String sql = "SELECT * FROM empdetail WHERE EmpID ="+txtEmpNo.getText();
            if(!txtEmpNo.getText().equals("")){
            
        
            rs = stmt.executeQuery(sql);
            rs.next();
                txtName.setText(rs.getString("EmpName"));
                txtAddress.setText(rs.getString("Address"));
                txtSuburb.setText(rs.getString("Suburb"));
                txtPostcode.setText(rs.getString("Postcode"));
                txtPhone.setText(rs.getString("HomePhone"));
                txtMobile.setText(rs.getString("Mobile"));
                txtEmail.setText(rs.getString("Email"));
            }
            else{
                msgMessage.showMessageDialog(this,"Please specify a 'Employee No' Value","Message",javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }
            stmt.close();
            connect.closeConnection(con);   
        }
        catch(SQLException sqle){
            msgMessage.showMessageDialog(this,sqle.toString(),"Error Message",javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnRetrieveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try{
            con = connect.connectToDatabase();
            stmt = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
            String sql = "SELECT * FROM empdetail WHERE EmpID = "+txtEmpNo.getText();
            rs = stmt.executeQuery(sql);
            while(rs.next()){
                rs.updateString("EmpName", txtName.getText());
                rs.updateString("Address", txtAddress.getText());
                rs.updateString("Suburb", txtSuburb.getText());
                rs.updateString("Postcode",txtPostcode.getText());
                rs.updateString("HomePhone", txtPhone.getText());
                rs.updateString("Mobile",txtMobile.getText());
                rs.updateString("Email", txtEmail.getText());
                rs.updateRow();
            }
            
            msgMessage.showMessageDialog(this,"Record updated successfuly","Message",javax.swing.JOptionPane.INFORMATION_MESSAGE);
            stmt.close();
            connect.closeConnection(con);
        }
        catch(SQLException sqle){
            msgMessage.showMessageDialog(this,sqle.toString(),"Error Message",javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        
            
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try{
            con = connect.connectToDatabase();
            stmt = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
            String sql2 = "SELECT * FROM empdetail WHERE EmpID = "+txtEmpNo.getText();
            rs = stmt.executeQuery(sql2);
            if(!rs.next()){
                msgMessage.showMessageDialog(this,"Record does not exist","Error Message",javax.swing.JOptionPane.ERROR_MESSAGE);
            }
            else{
                //rs.getString("EmpName");    //che
                String sql = "DELETE FROM empdetail WHERE EmpID = "+txtEmpNo.getText();

                stmt.executeUpdate(sql);
                msgMessage.showMessageDialog(this,"Record deleted","Message",javax.swing.JOptionPane.INFORMATION_MESSAGE);
                txtEmpNo.setText("");
                txtName.setText("");
                txtAddress.setText("");
                txtSuburb.setText("");
                txtPostcode.setText("");
                txtPhone.setText("");
                txtMobile.setText("");
                txtEmail.setText("");
                stmt.close();
                connect.closeConnection(con);
            }
        }
        catch(SQLException sqle){
            msgMessage.showMessageDialog(this,sqle.toString(),"Error Message",javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtSuburbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSuburbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSuburbActionPerformed
    
    private void btnSubmitQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitQueryActionPerformed
        try{
            con = connect.connectToDatabase();
            stmt = con.createStatement();
            String sql = txtQuery.getText();
            rs = stmt.executeQuery(sql);
            ResultSetMetaData rsMeta = rs.getMetaData();
            int count = 0;
         
            TableModel model = new TableModel(rs);
            tblDetails.setModel(model);
            count = model.getRowCount();
            
            txtNumberOfRecord.setText(String.valueOf(count));
            connect.closeConnection(con);
        }
        catch(SQLException sqle){
            msgMessage.showMessageDialog(this,sqle.toString(),"Error Message",javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSubmitQueryActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        PrintWriter write;
        try{
            
            write = new PrintWriter(txtFilePath.getText());
            
            for(int col = 0; col<tblDetails.getColumnCount(); col++){
                write.write(tblDetails.getColumnName(col)+" | ");
            }
            write.write("\r\n");
            for(int rec =0; rec<tblDetails.getRowCount(); rec++){
                write.write("\r\n");
            
                for(int col = 0; col<tblDetails.getColumnCount(); col++){
                    write.print(tblDetails.getValueAt(rec, col)+" | ");
                  
                }
            }
            write.close();
            msgMessage.showMessageDialog(this,"File saved successfully","Message",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
            
        } 
        
        catch(IOException ioe){
            msgMessage.showMessageDialog(this,ioe.toString(),"Error Message",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatabaseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatabaseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatabaseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatabaseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatabaseFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DbDriver;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnRetrieve;
    private javax.swing.JButton btnSubmitQuery;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JOptionPane msgMessage;
    private javax.swing.JPanel panEmployeeDetails;
    private javax.swing.JPanel panMetaData;
    private javax.swing.JPanel panQuery;
    private javax.swing.JTable tblDetails;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtDbType;
    private javax.swing.JTextField txtDbVersion;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmpNo;
    private javax.swing.JTextField txtFilePath;
    private javax.swing.JTextField txtMobile;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNumberOfRecord;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPostcode;
    private javax.swing.JTextField txtQuery;
    private javax.swing.JTextField txtSuburb;
    private javax.swing.JTextArea txtTableColumns;
    private javax.swing.JTextField txtTableName;
    // End of variables declaration//GEN-END:variables
}
